---
title             : "The title"
shorttitle        : "Title"

author: 
  - name          : "First Author"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - Conceptualization
      - Writing - Original Draft Preparation
      - Writing - Review & Editing
  - name          : "Ernst-August Doelle"
    affiliation   : "1,2"
    role:
      - Writing - Review & Editing

affiliation:
  - id            : "1"
    institution   : "Wilhelm-Wundt-University"
  - id            : "2"
    institution   : "Konstanz Business School"

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
  
  Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.
  
  One sentence clearly stating the **general problem** being addressed by  this particular study.
  
  One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
  
  Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.
  
  One or two sentences to put the results into a more **general context**.
  
  Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
if(!"papaja" %in% rownames(installed.packages())) {
  devtools::install_github("crsh/papaja")
}
library("papaja")
r_refs("r-references.bib")
library(tidyverse)
library(readxl)
library(patchwork)
library(arsenal)
knitr::opts_chunk$set(
  fig.height = 6,
  fig.width = 8,
  message = F,
  echo = F,
  warning = F
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis",
  digits = 3
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

my_controls <- tableby.control(
  total = F,
  test = F,
  # No test p-values yet
  numeric.stats = c("meansd", "medianq1q3", "range"),
  cat.stats = c("countpct"),
  stats.labels = list(
    meansd = "Mean (SD)",
    medianq1q3 = "Median (Q1, Q3)",
    range = "Min - Max",
    Nmiss2 = "Missing",
    countpct = "N (%)"
  )
)
```

```{r load_data}
hate_df =
  read_csv(here::here("HateCrimes.csv"),
           col_types =
             "cffdddddd") %>%
  janitor::clean_names() %>%
  drop_na() %>%
  filter(hate_crimes_per_100k_splc < 1.2) %>%
  mutate(across(unemployment:urbanization, as.factor)) %>% 
  rename(
    education = perc_population_with_high_school_degree,
    hate_crimes = hate_crimes_per_100k_splc,
    median_income = median_household_income
  )
```



# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

```{r descriptive, results = "asis"}
hate_df %>%
  select(-state) %>%
  tableby( ~ ., data = ., control = my_controls) %>%
  summary(., title = "Descriptive Statistics",text = TRUE) %>%
  knitr::kable(
    longtable = T,
    caption = "caption"
  )
```

```{r model,results = "asis"}
hate_md =
  hate_df %>%
  nest(.) %>%
  mutate(model_1 =
           map(.x = data,
               ~ lm(
                 log(hate_crimes) ~ gini_index,
                 data = .x
               )),
         model_2 =
           map(
             .x = data,
             ~ lm(
               log(hate_crimes) ~ 
                 gini_index + education,
               data = .x
             )
           ),
         model_3 =
           map(
             .x = data,
             ~ lm(
               log(hate_crimes) ~
                 gini_index +
                 education +
                 unemployment + unemployment:gini_index,
               data = .x
             )
           )) %>% 
  select(-data) %>% 
  pivot_longer(
    model_1:model_3,
    names_to = "model",
    values_to = "value"
  ) %>% 
  mutate(value = map(value,broom::tidy)) %>% 
  unnest(c(value)) %>% 
  janitor::clean_names() %>%
  filter(term != "(Intercept)")

hate_md %>% 
  mutate(
    lwr = estimate - qt(0.975, 44) * std_error,
    upr = estimate + qt(0.975, 44) * std_error,
    across(where(is.numeric),  ~ as.character(round(.x, 3))),
    result =
      str_c(estimate,"(",lwr,",",upr,")",sep = " ")
  ) %>% 
  select(model,term,result) %>% 
  pivot_wider(
    names_from = model,
    values_from = result
  ) %>% 
  apa_table(
    .,
    caption = "Association table",
    note = "some note",
    landscape = TRUE
  )
```


# Discussion


\newpage

# References

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id="refs" custom-style="Bibliography"></div>
\endgroup

# Appendix

```{r correlation}
hate_df %>% 
  select(where(is.numeric)) %>% 
  cor() %>% 
  corrplot::corrplot(
    method = "circle",
    type = "lower",
    addCoef.col = "black",
    diag = T,
    title = "Correlation Plot",
    tl.srt = 0
  )

```

